### ISSUE TITLE
My robot looks perfect in my browser...

### ISSUE THREAD

**Issue by alicaudle** [alicaudle/exploding-robot-head#1]
but then markbot thinks it looks like shit. It's showing me completely different visuals for my robot than my browser is– OOOOOOH...it's showing me what my robot looks like when I shrink the browser. Well. That's frustrating. HELP!! How do I keep it from getting messed up in the smaller browser?
@thomasjbradley

Ali

**Comment by thomasjbradley** [comment]
You’ve got `position: relative` on the wrong thing—it always goes on a parent element. So it should actually be on `.robot`
